export type Property = {
  id: string;
  slug: string;
  code: string;
  title: string;
  description: string;
  short_description: string;
  purpose: string;
  type: string;
  city: string;
  neighborhood: string;
  condominium: string;
  state: string;
  address: string;
  map_mode: string;
  price: number;
  condo_fee: number;
  iptu: number;
  show_price: boolean;
  area: number;
  land_area: number;
  bedrooms: number;
  suites: number;
  bathrooms: number;
  parking: number;
  floor: number;
  year: number;
  status: string;
  active: boolean;
  featured: boolean;
  tag: string;
  sort_order: number;
  images: string[];
  captions: string[];
  features: string[];
  financing: boolean;
  fgts: boolean;
  exchange: boolean;
  video: string;
  tour: string;
  seo_title: string;
  seo_description: string;
  created_at: string;
  updated_at: string;
};
export type Lead = {
  consent_at?: string;
  consent_version?: string;
  id: string;
  name: string;
  phone: string;
  email: string;
  property_id: string | null;
  origin: string;
  message: string;
  status: string;
  utms: Record<string, string>;
  created_at: string;
};
export type Content = {
  id: string;
  kind: string;
  title: string;
  body: string;
  extra: string;
  sort_order: number;
};
export type Settings = Record<string, string>;
